### ISSUE TITLE
Automated Postgres Backup Always Empty

### ISSUE THREAD

**Issue by brunoh3art** [Dokploy/dokploy#1382]
### To Reproduce

1. Deploy the Postgres Template with automated backups enabled.
2. Configure S3 (DigitalOcean Buckets) as the backup storage.
3. Ensure that the database has live data.
4. Wait for the backup job to run.
5. Check the uploaded .sql.gz file in the bucket.
6. Extract the file (gunzip xx.sql.gz) and inspect the contents.

🔹 Result: The backup file is always 20 bytes and contains no actual data.

### Current vs. Expected behavior

✅ Expected: The backup should contain a full dump of the PostgreSQL database.
❌ Current: The backup file is created daily but remains empty (only 20 bytes).

### Provide environment information

```bash
Operating System:
  OS: Ubuntu 24.10
  Arch: arm64
Dokploy version: 0.18.4'

VPS Provider: DigitalOcean.
Database
```

### Which area(s) are affected? (Select all that apply)

Databases

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

I am interested in contributing and investigating this issue but I am not familiar with the core codebase.

Could you provide guidance on where the backup logic is implemented? Any pointers would be very helpful!

### Will you send a PR to fix it?

Yes

**Comment by JowaDev** [comment]
Exactly the same for me

**Comment by Siumauricio** [comment]
I think it's not a bug as such, I think it's more about how we are giving the user the way to fill the s3 bucket credentials, there are many fields that are optional which shouldn't be, I tested with hetzner storage and digitalocean and it works fine, I will update the test connection to be more restrictive with the properties.

**Comment by JowaDev** [comment]
Okey but I have three databases with backup enabled, two of them work for the backup but not the last. Three postgres db, with S3 compatible provider, database name are correctly filled, could it be a schema issue ? If it isn't the default schema ?

**Comment by Siumauricio** [comment]
are you using the same S3 Destination for the 3 databases, the only reason I get 20bytes is because the database does not exist, so it is difficult to know why in 2 databases it works and in 3 it does not.

**Comment by Gity37** [comment]
I opened a PR that maybe fix this problem in some cases:
https://github.com/Dokploy/dokploy/pull/1431

If your database root passwords have quotes within or leading or trailing whitespaces then this might be your case.
There should be a discrepancy between your root password shown in Dokploy and the actual service root password.

In my case I fixed this backup problem by changing the root password to the one that Dokploy says it's your password.

**Comment by JowaDev** [comment]
> are you using the same S3 Destination for the 3 databases, the only reason I get 20bytes is because the database does not exist, so it is difficult to know why in 2 databases it works and in 3 it does not.

The database exists, but I think it's about the password, the last char contains this : #

I have upgrade to the latest version of Dokploy, it still doesn't work...
