### ISSUE TITLE
After the application is deleted and recreated with the same name, it automatically creates an image.

### ISSUE THREAD

**Issue by xXAvoraXx** [Dokploy/dokploy#2739]
### To Reproduce

**To Reproduce**
1. Create a new application in the Dokploy panel using a Dockerfile.
2. Delete the application.
3. Create a new application with the same name as the deleted one.
4. Do not provide any configuration (leave it completely empty).
5. Observe that Dokploy automatically builds a Docker image for the empty application.

### Current vs. Expected behavior

- **Current behavior:** The new, empty application automatically builds a Docker image without any user-provided configuration.
- **Expected behavior:** The new application should remain empty and should not build an image automatically unless a Dockerfile or Docker image is explicitly provided.

### Provide environment information

```bash
Dokploy panel version: v0.25.4
Browser: Chrome 140
OS: Windows 11
```

### Which area(s) are affected? (Select all that apply)

Application

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

I created an application in the Dokploy panel using a Dockerfile. Later, I deleted that application because I decided to use a Docker image instead of a Dockerfile. Then, I created a new application with the exact same name as the deleted one. Without adding any configuration, I noticed that the newly created empty application automatically built an image by itself.

Is this expected behavior, or could this be a bug?

<img width="1509" height="210" alt="Image" src="https://github.com/user-attachments/assets/8f9eb7d0-7340-45e3-8231-cf35c74cd4c9" />

<img width="1541" height="568" alt="Image" src="https://github.com/user-attachments/assets/d092cee2-1c5f-4894-aeec-73f1653bfc9f" />

### Will you send a PR to fix it?

No

**Comment by xXAvoraXx** [comment]
Even though I deleted the application and the image, it keeps creating images on its own.

**Comment by xXAvoraXx** [comment]
<img width="1200" height="245" alt="Image" src="https://github.com/user-attachments/assets/9d15a36c-9c81-4f06-b1e3-31d14023bb80" />

I restarted the server to get rid of the bug, but I noticed that it keeps creating containers indefinitely. Dokploy is creating them, and there is no setting on my Dokploy screen that allows me to stop this

**Comment by xXAvoraXx** [comment]
The root cause of the issue was related to an active Docker service that remained running even after the application was deleted from the Dokploy panel. This residual service continued to run in the background and could trigger automatic image builds or redeployments, causing unexpected behavior when a new application was created with the same name. Once the leftover Docker service was manually removed using the Docker CLI, the problem was resolved. Therefore, the issue was not caused by Dokploy's internal cache or Redis state, but rather by an orphaned Docker service that was still active on the system.

**Comment by Siumauricio** [comment]
Hello, I tried to follow the steps to reproduce the issue, but I couldn't reproduce it.

Could you give me more details about the steps you followed? If you can attach images and configurations you use, that would help me understand the problem better. I don't think I understood the steps very well.

**Comment by xXAvoraXx** [comment]
I think the issue might be related to caching. I performed multiple consecutive deployment attempts while testing my applications, so it might have gotten stuck due to that. The reason I think this is because after each deployment, the previous container, image, and volume aren’t automatically deleted — so I have to remove them manually. To do that, I went to the “Web server > space” section and clicked through everything from top to bottom.


<img width="1311" height="611" alt="Image" src="https://github.com/user-attachments/assets/f3068c00-d4d6-4da5-95c9-5dfe982106a1" />

Another possibility is that during an automatic deployment, I clicked the “cancel” button several times, but since the “loading” icon was still showing, I followed the same steps (“Web server > space”) again to clear the cache.

I believe the issue might have occurred as a result of these actions. I solved it by checking the Docker service list and manually deleting the relevant service.

My guess is that there might be a disconnect between the deletion of the Dokploy service and the corresponding Docker service.

**Comment by Siumauricio** [comment]
Dokploy does not delete old images. A new build probably reused the Docker layer cache, which is why it appears to use the same image. However, if you create a new application service, it will use a completely different image, because the appName associated with an application is unique and does not repeat itself. 

Although I still do not understand how to reproduce your problem, as I find the steps confusing to follow, I see that you have resolved the issue, so I will close this problem. I see that no one else has reported it.

**Comment by xXAvoraXx** [comment]
@Siumauricio I think a bug occurred due to the race condition. I haven't experienced this problem again.

**Comment by jon91** [comment]
- list docker service (swarm) `docker service ls`
- remove orphaned service `docker service rm <NAME>`
- repeat as needed
